# Generated by Django 3.2.5 on 2021-07-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryList', '0003_auto_20210724_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='users',
            new_name='shared_by',
        ),
    ]
